# Generated by Django 3.2.13 on 2022-05-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapicheck', '0002_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='notification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
